version: 2
jobs:
  test:
    working_directory: /opt/mysql-server
    docker:
      - image: ryosan470/mysql-dev-docker
    steps:
      - checkout
      - run:
          name: Copy code to storage directory
          command: cp -r src storage/
      - run:
          name: Build your plugin
          command: |
            ./dev/build.sh
      - run:
          name: Launch MySQL
          command: |
            ./dev/serve.sh
      - run:
          name: Wait for launching MySQL
          command: |
            dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Install plugin to MySQL
          command: |
            /dev/install_plugin.sh
      - run:
          name: Show engine
          command: |
            mysql -uroot -e "SHOW ENGINES"

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
