version: 2
jobs:
  test:
    working_directory: /opt/mysql-server
    docker:
      - image: ryosan470/mysql-dev-docker
    steps:
      - checkout
      - run:
          name: Copy tool to root directory
          command: |
            rm -r storage
            mkdir -p storage
            cp -r src/* storage/
            cp dev/*.sh ./
      - run:
          name: Build your plugin
          command: |
            ./build.sh
      - run:
          name: Launch MySQL
          command: |
            ./serve.sh
      - run:
          name: Wait for launching MySQL
          command: |
            dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Install plugin to MySQL
          command: |
            ./install_plugin.sh
      - run:
          name: Show engine
          command: |
            mysql -uroot -e "SHOW ENGINES"

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
