version: 2
jobs:
  test:
    working_directory: /opt/mysql-server
    docker:
      - image: ryosan470/mysql-dev-docker
    steps:
      - checkout
      - run:
          name: Copy tool to root directory
          command: |
            rm -r storage
            mkdir -p storage
            cp -r src/* storage/
            cp dev/*.sh ./
      - run:
          name: Build your plugin
          command: |
            cmake .
            ./build.sh
      - run:
          name: Launch MySQL
          command: |
            bash /entrypoint.sh mysqld
          background: true
          environments:
            MYSQL_ALLOW_EMPTY_PASSWORD=true
      - run:
          name: Wait for launching MySQL
          command: |
            dockerize -wait unix:///var/run/mysqld/mysqlx.sock -timeout 5m
      - run:
          name: Install plugin to MySQL
          command: |
            ./install_plugin.sh
      - run:
          name: Show engine
          command: |
            mysql -uroot -e "SHOW ENGINES"

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
